
import { ContentType } from '../components/content/ContentTypeSelector';

export const generateMockContent = (
  contentType: ContentType,
  listingDetails: any
): string => {
  const { address, price, bedrooms, bathrooms, squareFootage, highlights } = listingDetails;
  const formattedAddress = address || '123 Main Street, Anytown, CA 12345';
  const formattedPrice = price || '$850,000';
  const hasImages = listingDetails.images && listingDetails.images.length > 0;
  
  // Image reference text to include in appropriate content types
  const imageReference = hasImages && ['instagram', 'facebook', 'linkedin', 'twitter', 'twitter/x', 'x', 'tiktok'].includes(contentType.platform.toLowerCase())
    ? "[Image will be attached when posting]\n\n"
    : "";

  // Base templates based on content type
  switch (contentType.id) {
    // Coming Soon
    case 'coming-soon-facebook':
      return `${imageReference}🏡 COMING SOON! 🏡\n\nExcited to announce a beautiful ${bedrooms || '4'} bed, ${bathrooms || '3'} bath home coming to the market next week in the heart of ${formattedAddress.split(',')[1] || 'Anytown'}!\n\n${highlights || 'Features include renovated kitchen, hardwood floors, and a spacious backyard perfect for entertaining.'}\n\nPrice: ${formattedPrice}\n\nContact me for early showings before it hits the market!`;
    
    case 'coming-soon-instagram':
      return `${imageReference}🔑 SNEAK PEEK 🔑\n\nThis gorgeous ${bedrooms || '4'} bedroom home is hitting the market next week! Located in desirable ${formattedAddress.split(',')[1] || 'Anytown'} and priced at ${formattedPrice}.\n\n👀 Early birds get first dibs!\n\n#ComingSoon #RealEstate #NewListing #${formattedAddress.split(',')[1]?.replace(/\s/g, '') || 'Anytown'}RealEstate`;
    
    // LinkedIn content
    case 'linkedin-listing':
      return `${imageReference}Excited to share a new property coming to the market!\n\nI'm pleased to present this exceptional ${bedrooms || '4'} bedroom, ${bathrooms || '3'} bathroom home in ${formattedAddress.split(',')[1] || 'Anytown'}. At ${formattedPrice}, this property offers incredible value with ${squareFootage || '2,500'} square feet of thoughtfully designed living space.\n\nKey features include:\n• ${highlights?.split('.')[0] || 'Renovated kitchen with high-end appliances'}\n• ${highlights?.split('.')[1]?.trim() || 'Spacious primary suite with en-suite bathroom'}\n• ${highlights?.split('.')[2]?.trim() || 'Excellent location near top schools and amenities'}\n\nInterested in scheduling a viewing or learning more? Connect with me directly.\n\n#RealEstate #NewListing #PropertyForSale #${formattedAddress.split(',')[1]?.replace(/\s/g, '') || 'Anytown'}`;
    
    // TikTok content
    case 'tiktok-property-tour':
      return `${imageReference}Wait till you see this INCREDIBLE ${bedrooms || '4'} bedroom home in ${formattedAddress.split(',')[1] || 'Anytown'} 🤯\n\nPriced at ONLY ${formattedPrice} with:\n- ${highlights?.split('.')[0]?.toLowerCase() || 'renovated kitchen with top appliances'}\n- ${highlights?.split('.')[1]?.toLowerCase()?.trim() || 'huge primary suite'}\n\nDM me for a private showing before it's gone! #RealEstateTikTok #DreamHome #HouseTour`;
    
    case 'coming-soon-email':
      return `Subject: Exclusive Preview: Stunning Property Coming to ${formattedAddress.split(',')[1] || 'Anytown'} Next Week\n\nDear [Client Name],\n\nI'm reaching out with an exclusive opportunity to preview a remarkable property before it officially hits the market next week.\n\nProperty Details:\n- ${bedrooms || '4'} bedrooms, ${bathrooms || '3'} bathrooms\n- ${squareFootage || '2,500'} square feet of living space\n- Located at ${formattedAddress}\n- Offered at ${formattedPrice}\n\nKey Features:\n${highlights || '• Completely renovated kitchen with stainless steel appliances\n• Hardwood floors throughout the main level\n• Large primary suite with walk-in closet\n• Spacious backyard with covered patio\n• Excellent school district'}\n\nI have availability for private showings this weekend before the property goes live on the MLS. This gives you a valuable opportunity to see the home without competition from other buyers.\n\nPlease let me know if you'd like to schedule a viewing or if you have any questions about this exciting new listing.\n\nBest regards,\n[Your Name]`;
    
    case 'property-teaser-video-script':
      return `[Opening Shot: Exterior of home with address numbers visible]\n\nVOICEOVER: "Something special is coming to ${formattedAddress.split(',')[1] || 'Anytown'}..."\n\n[Pan to show street view and neighborhood]\n\nVOICEOVER: "Nestled in one of the area's most desirable neighborhoods..."\n\n[Quick cuts of key rooms - kitchen, living room, primary bedroom]\n\nVOICEOVER: "This exceptional ${bedrooms || '4'} bedroom, ${bathrooms || '3'} bathroom home offers ${squareFootage || '2,500'} square feet of thoughtfully designed living space."\n\n[Highlight special feature - backyard, view, etc.]\n\nVOICEOVER: "${highlights?.split('.')[0] || 'Featuring a stunning renovated kitchen and hardwood floors throughout'}..."\n\n[Final exterior shot with agent standing in front]\n\nVOICEOVER: "Coming next week, priced at ${formattedPrice}. Contact me for an exclusive preview before it hits the market!"\n\n[End with agent contact details on screen]`;
    
    case 'coming-soon-flyer':
      return `COMING SOON\n\n${formattedAddress}\n\nPrice: ${formattedPrice}\nBedrooms: ${bedrooms || '4'}\nBathrooms: ${bathrooms || '3'}\nSquare Footage: ${squareFootage || '2,500'} sq ft\n\nProperty Highlights:\n${highlights || '• Completely renovated kitchen with stainless steel appliances\n• Hardwood floors throughout the main level\n• Large primary suite with walk-in closet\n• Spacious backyard with covered patio\n• Excellent school district'}\n\nContact [Your Name] for an exclusive showing before this property hits the market!\nPhone: [Your Phone]\nEmail: [Your Email]\nBroker: [Your Brokerage Information]`;
    
    // Just Listed
    case 'just-listed-facebook':
      return `${imageReference}🏡 JUST LISTED! 🏡\n\nProud to present this beautiful ${bedrooms || '4'} bed, ${bathrooms || '3'} bath home in ${formattedAddress.split(',')[1] || 'Anytown'}!\n\n✅ ${squareFootage || '2,500'} square feet\n✅ ${highlights?.split('.')[0] || 'Gorgeous renovated kitchen'}\n✅ ${highlights?.split('.')[1] || 'Spacious backyard perfect for entertaining'}\n\nOffered at ${formattedPrice} - this won't last long!\n\nDM me for a showing or more information.`;
    
    case 'just-listed-instagram':
      return `${imageReference}💎 NEW LISTING ALERT 💎\n\nSwipe through to see this immaculate ${bedrooms || '4'} bed/${bathrooms || '3'} bath home just listed at ${formattedPrice}!\n\nLocated in the heart of ${formattedAddress.split(',')[1] || 'Anytown'}, this ${squareFootage || '2,500'} sq ft home features ${highlights?.split('.')[0]?.toLowerCase() || 'a gorgeous renovated kitchen'} and ${highlights?.split('.')[1]?.toLowerCase() || 'spacious backyard perfect for entertaining'}.\n\nContact me for a showing before it's gone!\n\n#JustListed #RealEstate #${formattedAddress.split(',')[1]?.replace(/\s/g, '') || 'Anytown'}RealEstate #NewListing #DreamHome`;
    
    // X/Twitter content
    case 'twitter-listing':
    case 'x-listing':
      return `${imageReference}🏠 JUST LISTED: Stunning ${bedrooms || '4'} bed, ${bathrooms || '3'} bath home in ${formattedAddress.split(',')[1] || 'Anytown'} for ${formattedPrice}!\n\nFeatures ${highlights?.split('.')[0]?.toLowerCase() || 'renovated kitchen'} and ${squareFootage || '2,500'} sq ft of living space.\n\nDM for details! #RealEstate #JustListed #${formattedAddress.split(',')[1]?.replace(/\s/g, '') || 'Anytown'}`;
    
    case 'property-description':
      return `EXCEPTIONAL ${formattedAddress.split(',')[1] || 'ANYTOWN'} HOME WITH MODERN AMENITIES\n\nWelcome to ${formattedAddress}, a stunning ${bedrooms || '4'} bedroom, ${bathrooms || '3'} bathroom residence offering ${squareFootage || '2,500'} square feet of thoughtfully designed living space.\n\nAs you enter, you'll be impressed by the bright, open floor plan that seamlessly connects the living spaces. The heart of this home is the ${highlights?.includes('kitchen') ? highlights.split('.').find(h => h.includes('kitchen')) || 'gourmet kitchen featuring high-end appliances, custom cabinetry, and stone countertops' : 'gourmet kitchen featuring high-end appliances, custom cabinetry, and stone countertops'}.\n\nThe spacious primary suite serves as a private retreat, complete with a luxurious en-suite bathroom and generous closet space. Additional bedrooms provide comfortable accommodations for family members or guests.\n\nOutdoor living is equally impressive with ${highlights?.includes('yard') || highlights?.includes('backyard') || highlights?.includes('outdoor') ? highlights.split('.').find(h => h.includes('yard') || h.includes('backyard') || h.includes('outdoor')) || 'a beautifully landscaped backyard offering the perfect setting for relaxation and entertainment' : 'a beautifully landscaped backyard offering the perfect setting for relaxation and entertainment'}.\n\nLocated in the highly desirable ${formattedAddress.split(',')[1] || 'Anytown'} neighborhood, this home offers convenient access to top-rated schools, shopping, dining, and recreation.\n\nOffered at ${formattedPrice}, this exceptional property represents the perfect blend of location, space, and modern amenities.`;
    
    // Social media posts
    case 'social-media-carousel':
      return `${imageReference}📸 PROPERTY SPOTLIGHT 📸\n\nTake a visual tour of this incredible ${bedrooms || '4'} bed, ${bathrooms || '3'} bath home in ${formattedAddress.split(',')[1] || 'Anytown'}!\n\nSwipe through to see all the stunning features of this ${formattedPrice} property, from the ${highlights?.split('.')[0]?.toLowerCase() || 'gorgeous renovated kitchen'} to the ${highlights?.split('.')[1]?.toLowerCase() || 'spacious backyard'}.\n\nDM for a private showing!\n\n#PropertyTour #RealEstate #DreamHome #HouseHunting`;
      
    case 'virtual-tour-promo':
      return `${imageReference}🏡 VIRTUAL TOUR AVAILABLE 🏡\n\nCan't make it to a showing? No problem! Experience this ${bedrooms || '4'} bed, ${bathrooms || '3'} bath ${formattedAddress.split(',')[1] || 'Anytown'} home from anywhere!\n\nClick the link in my bio to take a virtual walkthrough of this ${formattedPrice} property.\n\nFeatures include ${highlights?.split('.')[0]?.toLowerCase() || 'a gorgeous renovated kitchen'} and so much more!\n\n#VirtualTour #RealEstate #HouseTour #StayAtHomeShopping`;
    
    // Open House
    case 'open-house-instagram':
      return `${imageReference}🔑 OPEN HOUSE THIS WEEKEND! 🔑\n\nJoin me this Saturday and Sunday from 1-4PM to tour this beautiful ${bedrooms || '4'} bed, ${bathrooms || '3'} bath home at ${formattedAddress}.\n\nPriced at ${formattedPrice}, this won't last long!\n\nHighlights include ${highlights?.split('.').slice(0, 2).join(' and ').toLowerCase() || 'renovated kitchen and hardwood floors'}.\n\nBring your buyers! Refreshments will be served.\n\n#OpenHouse #RealEstate #HouseHunting #WeekendPlans`;
    
    // New content types from the 23 ideas list
    case 'google-business-profile':
      return `${imageReference}🏡 NEW LISTING ALERT: ${bedrooms || '4'} bed, ${bathrooms || '3'} bath home in ${formattedAddress.split(',')[1] || 'Anytown'}\n\nJust listed at ${formattedPrice}! This ${squareFootage || '2,500'} sq ft home features ${highlights?.split('.')[0]?.toLowerCase() || 'a gorgeous renovated kitchen'} and is located in a highly desirable neighborhood.\n\nContact me for a private showing or more information!\n\n#JustListed #RealEstate #NewHome`;
      
    case 'youtube-walkthrough':
      return `TITLE: Full Home Tour: Stunning ${bedrooms || '4'} Bedroom Home in ${formattedAddress.split(',')[1] || 'Anytown'} | ${formattedPrice}\n\nDESCRIPTION:\nWelcome to this comprehensive walkthrough of our newest listing at ${formattedAddress}. In this video, I'll take you through every room of this beautiful ${bedrooms || '4'} bedroom, ${bathrooms || '3'} bathroom home priced at ${formattedPrice}.\n\nSCRIPT:\n\n[Intro - Outside the home]\nHello everyone! I'm [Your Name] with [Your Brokerage], and today I'm excited to show you this beautiful home located in the heart of ${formattedAddress.split(',')[1] || 'Anytown'}.\n\n[Front Exterior]\nAs you can see, this home has excellent curb appeal with [describe exterior features]. Let's head inside and see what makes this property so special.\n\n[Entryway/Foyer]\nStepping inside, you're greeted by this welcoming entryway with [describe features].\n\n[Living Room]\nThe living room is spacious and bright, featuring [describe features].\n\n[Kitchen]\nNext, we have the kitchen, which is truly the heart of this home. It features ${highlights?.includes('kitchen') ? highlights.split('.').find(h => h.includes('kitchen'))?.toLowerCase() || 'high-end appliances, custom cabinetry, and beautiful countertops' : 'high-end appliances, custom cabinetry, and beautiful countertops'}.\n\n[Continue with other rooms...]\n\n[Conclusion]\nThank you for joining me on this tour of ${formattedAddress}. If you're interested in seeing this property in person, please contact me at [Your Contact Information]. Don't forget to like this video and subscribe to my channel for more property tours!\n\nTAGS: #HomeWalkthrough #RealEstateVideo #HouseTour #${formattedAddress.split(',')[1]?.replace(/\s/g, '') || 'Anytown'} #LuxuryRealEstate`;
      
    case 'buyer-feedback':
      return `${imageReference}💬 BUYER FEEDBACK: What People Are Saying About This Listing\n\nAfter multiple showings of our ${formattedAddress.split(',')[1] || 'Anytown'} property, here's what potential buyers have shared:\n\n"The kitchen is absolutely stunning - perfect for entertaining!" - Buyer from [Nearby City]\n\n"The primary bedroom feels like a private retreat." - Couple relocating to the area\n\n"Love how close it is to schools and parks." - Young family\n\nInteresting to note: Most buyers have been particularly impressed with ${highlights?.split('.')[0]?.toLowerCase() || 'the renovated kitchen and open floor plan'}.\n\nThis kind of feedback is valuable market intelligence! If you're curious what buyers might say about your home, let's talk.\n\n#BuyerInsights #RealEstateFeedback #MarketIntelligence`;
      
    case 'offer-story':
      return `${imageReference}🎯 EXCITING UPDATE ON MY LISTING!\n\nWhile I can't share confidential details, I can tell you that this ${bedrooms || '4'} bedroom home in ${formattedAddress.split(',')[1] || 'Anytown'} just received an offer that demonstrates the strong demand in our market right now!\n\nWhat made this property stand out? Buyers particularly loved ${highlights?.split('.')[0]?.toLowerCase() || 'the renovated kitchen'} and its prime location.\n\nThinking of selling? This might be the perfect time to capitalize on current market conditions. Let's connect!\n\n#RealEstateOffer #HotMarket #SellerOpportunity`;
      
    case 'seller-story':
      return `${imageReference}📖 THE STORY BEHIND THIS HOME\n\nEvery property has a story, and this one is special. I sat down with the sellers of ${formattedAddress} to learn what made this house their home for the past [X] years.\n\n"We bought this house when our children were young. What we'll miss most is [personal detail about the home]." - Seller\n\nTheir favorite memories were made in the ${highlights?.split('.').find(h => h.includes('kitchen') || h.includes('backyard') || h.includes('living'))?.toLowerCase() || 'backyard during summer barbecues'}, and they hope the new owners will create equally wonderful moments here.\n\nI'm honored to help transition this beloved home to its next chapter. Want to be part of its story? Let's talk.\n\n#HomeStories #SellerExperience #RealEstateLegacy`;
      
    case 'hero-feature':
      return `${imageReference}✨ FEATURE SPOTLIGHT: The Heart of This Home\n\nSome features truly define a property. For this ${formattedAddress.split(',')[1] || 'Anytown'} listing, it's definitely the ${highlights?.split('.')[0]?.toLowerCase() || 'stunning renovated kitchen'}.\n\nWhat makes it special:\n• Custom cabinetry extending to the ceiling for maximum storage\n• Oversized island perfect for both preparation and gathering\n• High-end appliances that blend functionality with beauty\n\nThis is the kind of feature that transforms a house into a dream home. It's not just about cooking—it's about creating a space where memories are made.\n\nInterested in seeing this feature in person? Contact me for a private showing!\n\n#DreamKitchen #HomeDesign #RealEstateFeature`;
      
    case 'behind-the-scenes':
      return `${imageReference}🎬 BEHIND THE SCENES: Preparing This Listing\n\nEver wonder what goes into preparing a home for market? Here's a peek behind the curtain of our ${formattedAddress} listing:\n\nBEFORE PHOTOS:\n• Professional staging to highlight the home's best features\n• Strategic decluttering to showcase space and flow\n• Minor repairs and touch-ups for that fresh, well-maintained look\n\nMARKETING PREP:\n• Professional photography with specialized lenses to capture true room dimensions\n• Detailed measurements and floor plan creation\n• Crafting compelling description that tells the home's story\n\nThe preparation process is where expertise truly matters—it's not just about selling a home, it's about presenting it in its absolute best light!\n\n#BehindTheScenes #ListingPrep #RealEstateMarketing`;
      
    case 'marketing-breakdown':
      return `${imageReference}📋 MARKETING STRATEGY: How We're Promoting This ${formattedPrice} Listing\n\nTransparency is important to me, so I wanted to share how we're marketing this exceptional property to ensure maximum exposure to qualified buyers:\n\nDIGITAL STRATEGY:\n• Targeted Facebook & Instagram ads to buyers searching in this price range\n• Virtual tour technology for remote buyers\n• Featured placement on major real estate platforms\n\nTRADITIONAL APPROACH:\n• Networking with top agents who work with relevant buyers\n• Direct mail to neighborhoods with likely move-up buyers\n• Strategic open houses to create buzz\n\nMeasuring Results:\n• [X] showings scheduled in the first week\n• [X] saved/favorited online\n• [X] direct inquiries from digital marketing\n\nMarketing isn't just about exposure—it's about finding the right buyer who will truly value what makes this home special.\n\n#RealEstateMarketing #ListingStrategy #MarketingInsights`;
      
    case 'walk-score-highlight':
      return `${imageReference}🚶‍♂️ LOCATION ADVANTAGE: This Property's Impressive Walk Score\n\nThis ${formattedAddress.split(',')[1] || 'Anytown'} home scores an excellent [X/100] on walkability!\n\nWithin easy walking distance:\n• Coffee shops: [Names of nearby coffee shops]\n• Restaurants: [Types of nearby restaurants]\n• Parks: [Names of nearby parks]\n• Shopping: [Types of nearby shopping]\n• Public transportation: [Nearby options]\n\nWith rising gas prices and growing interest in walkable neighborhoods, this location offers both convenience and long-term value. Today's buyers increasingly prioritize lifestyle and accessibility in their home search.\n\nWant to experience this walkable neighborhood for yourself? Contact me for a showing!\n\n#WalkScore #LocationAdvantage #WalkableNeighborhood`;
      
    case 'property-quiz':
      return `${imageReference}🤔 QUIZ TIME! Can you guess...\n\n1. Which room in this ${formattedAddress.split(',')[1] || 'Anytown'} listing gets the most natural light?\n\n2. What unexpected feature makes the primary bathroom so special?\n\n3. How many total rooms does this property have?\n\n4. What hidden bonus space might surprise you during a tour?\n\nComment your guesses below! I'll reveal the answers tomorrow.\n\nHint: One of these features is completely unique to this property and rarely found in similar homes in the area.\n\nWant to see for yourself? Contact me for a showing of this ${formattedPrice} property!\n\n#RealEstateQuiz #PropertyFeatures #GuessTheRoom`;
      
    case 'cma-mailing':
      return `Subject: Property Value Update for ${formattedAddress.split(',')[1] || 'Anytown'} - Insights From Recent Sale\n\nDear [Neighbor's Name],\n\nAs a resident of ${formattedAddress.split(',')[1] || 'Anytown'}, I thought you'd be interested in some recent market activity in our neighborhood. My listing at ${formattedAddress} was recently [listed/sold] at ${formattedPrice}, which offers valuable insight into current property values in our area.\n\nBased on this recent activity, homes similar to yours in size and style are currently valued between [Price Range]. This represents a [X]% [increase/adjustment] from this time last year.\n\nIf you've been curious about your home's current market value, I'd be happy to provide you with a complimentary, no-obligation Comparative Market Analysis that's specific to your property.\n\nI've helped [X] homeowners in ${formattedAddress.split(',')[1] || 'Anytown'} sell their homes this year, and I'm always available to answer any questions you might have about our local real estate market.\n\nWould you like to schedule a quick 15-minute consultation to discuss your specific property? I'm available [Days/Times] next week.\n\nBest regards,\n[Your Name]\n[Your Contact Information]`;
      
    case 'live-open-house':
      return `LIVE OPEN HOUSE SCRIPT - ${formattedAddress}\n\n[BEFORE GOING LIVE]\n• Test internet connection throughout the home\n• Prepare talking points for each room\n• Have property details handy\n\n[INTRODUCTION - OUTSIDE THE HOME]\n"Hello everyone, and welcome to my live open house tour! I'm [Your Name] with [Your Brokerage], and today I'm excited to show you this beautiful ${bedrooms || '4'} bedroom, ${bathrooms || '3'} bathroom home in ${formattedAddress.split(',')[1] || 'Anytown'}, currently offered at ${formattedPrice}.\n\nAs you join, feel free to post any questions in the comments, and I'll answer them as we go through the home. I'll also be taking requests if there's a specific feature you want to see up close."\n\n[MOVING THROUGH THE HOME]\n• Front entrance: "Let's start with the welcoming entrance..."\n• Living areas: "Notice the [specific features]..."\n• Kitchen: "This kitchen features [specific details]..."\n• Primary bedroom: "The primary suite offers [specific features]..."\n• Outdoor space: "Step outside to see this amazing [yard/patio/deck]..."\n\n[WRAP-UP]\n"Thank you all for joining my live open house tour today! If you're interested in seeing this property in person, I'm hosting an in-person open house this [Day] from [Time] to [Time]. You can also contact me directly at [Your Phone/Email] to schedule a private showing.\n\nDon't forget to share this video with anyone you know who might be interested in this amazing home. Thanks for watching!"`;
      
    case 'story-poll':
      return `INSTAGRAM/FACEBOOK STORY POLL IDEAS FOR ${formattedAddress}:\n\n1. MAIN POLL:\nWould you move for a kitchen like this? 👇\n• YES! Dream kitchen alert! 😍\n• Maybe, if the price is right 💰\n\n2. BEDROOM POLL:\nWhich bedroom would you choose?\n• The primary suite with walk-in closet\n• The corner bedroom with bay windows\n\n3. OUTDOOR SPACE POLL:\nBackyard goals? 🌿\n• Absolutely perfect for entertaining!\n• I'd prefer a different layout\n\n4. NEIGHBORHOOD POLL:\nWhat's the most important nearby amenity?\n• Parks and recreation\n• Great schools\n• Shopping and dining\n• Easy commute\n\n5. DESIGN POLL:\nWhat's your favorite feature?\n• Open concept layout\n• Updated kitchen\n• Primary bathroom\n• Outdoor space\n\nFOLLOW-UP STRATEGY:\nSend a direct message to everyone who engages with your poll:\n"Hi [Name]! I noticed you were interested in the [feature] of my new listing. Would you like me to send you more information or schedule a showing?"\n\n#StoryPolls #RealEstateEngagement #InteractiveMarketing`;
      
    case 'marketing-case-study':
      return `# REAL ESTATE MARKETING CASE STUDY: ${formattedAddress.split(',')[1] || 'Anytown'} Property\n\nFor fellow real estate professionals and marketing enthusiasts, I wanted to share a transparent breakdown of how we marketed our recent ${formattedPrice} listing in ${formattedAddress.split(',')[1] || 'Anytown'}.\n\n## THE STRATEGY\n\n### Pre-Listing Phase (2 weeks):\n• "Coming Soon" teaser campaign\n• Seller story video recording\n• Professional photography and videography\n• Property website creation\n\n### Launch Week:\n• Multi-platform announcement (organic + paid)\n• Email blast to database\n• Circle prospecting to 200 nearby homeowners\n• Broker open house\n\n### Ongoing Campaign (3 weeks):\n• Weekly content schedule across all platforms\n• Targeted Facebook/Instagram ads ($[Amount] spend)\n• Open houses with theme elements\n• Follow-up system for all inquiries\n\n## THE RESULTS\n\n• Total Showings: [Number]\n• Website Visitors: [Number]\n• Social Media Engagement: [Number]\n• Qualified Leads Generated: [Number]\n• Days on Market: [Number]\n• Final Sale: [Details if appropriate]\n\n## KEY LEARNINGS\n\n1. The "hero feature" posts focusing on the ${highlights?.split('.')[0]?.toLowerCase() || 'kitchen'} generated 3x more engagement than general listing posts\n\n2. Video content consistently outperformed static images\n\n3. The seller story element created emotional connection with potential buyers\n\nFor my fellow agents: I'm happy to share my content calendar template and ad targeting strategy. DM me if you'd find that valuable!\n\n#RealEstateMarketing #MarketingCaseStudy #RealEstateStrategy`;
      
    case 'email-newsletter':
      return `Subject: Behind the Scenes: Insights from Our Latest ${formattedAddress.split(',')[1] || 'Anytown'} Listing\n\nDear [Name],\n\nI hope this email finds you well! Today, I wanted to share some insights from our latest listing that might be valuable whether you're considering selling in the future or simply interested in real estate trends.\n\n### PROPERTY SPOTLIGHT\n\nOur newest listing at ${formattedAddress} offers ${bedrooms || '4'} bedrooms and ${bathrooms || '3'} bathrooms, priced at ${formattedPrice}. While the property is beautiful, what's been most interesting is what we've learned through the marketing process.\n\n### MARKET INSIGHTS\n\n**What Buyers Are Looking For Right Now:**\nThrough our showing feedback, we've discovered that today's buyers are particularly focused on:\n\n1. Work-from-home spaces with natural light\n2. Updated kitchens with thoughtful storage solutions\n3. Outdoor living areas that extend the functional square footage\n\n**Current Market Conditions:**\nIn the ${formattedAddress.split(',')[1] || 'Anytown'} area, we're seeing:\n• Average days on market: [Number]\n• Average sale to list price ratio: [Percentage]\n• Inventory levels: [Description]\n\n### SELLING TIP OF THE MONTH\n\nIf you're considering selling in the next 6-12 months, one smart investment might be [specific recommendation based on current buyer preferences].\n\nOur recent sellers who focused on this aspect before listing saw an average return of [X]% on that specific investment.\n\n### WHAT'S HAPPENING LOCALLY\n\n[Brief mention of local development, community events, or news that impacts real estate values]\n\nAs always, if you have any questions about the real estate market or your specific property, I'm just a phone call or email away.\n\nBest regards,\n[Your Name]\n\nP.S. If you know anyone who might be interested in our ${formattedAddress} listing, I'd appreciate you forwarding this email to them!`;
    
    // Default content
    default:
      return `${imageReference}Content for ${contentType.title} targeting the ${contentType.platform} platform.\n\nThis will highlight your ${formattedAddress} property priced at ${formattedPrice} with its ${bedrooms || '4'} bedrooms and ${bathrooms || '3'} bathrooms.\n\nKey features include: ${highlights || 'renovated kitchen, hardwood floors, and spacious backyard'}.`;
  }
};

export const generateAllContent = (
  contentTypes: ContentType[],
  listingDetails: any
): Record<string, string> => {
  const result: Record<string, string> = {};
  
  contentTypes.forEach(type => {
    result[type.id] = generateMockContent(type, listingDetails);
  });
  
  return result;
};
